name: Github Labeler
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  apply-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v4