name: Test depends workflow

# on:
#   # pull_request:
#   #   types: [opened, synchronize, reopened, ready_for_review]
#   workflow_run:
#     workflows: ["Github Labeler"]
#     types: 
#       - completed

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering workflow passed'