name: Test

on:
  workflow_run:
    workflows:
      - Github Labeler
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering workflow passed'