name: Test depends Github Labeler
on:
  workflow_run:
    workflows:
      - Github Labeler
    types:
      - completed

# on:
#   workflow_call:
#     workflows:
#       - Github Labeler
#     types:
#       - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - name: 'Trigger'
        run: echo 'The triggering workflow passed'
